PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

CREATE TABLE redir (
	id INTEGER PRIMARY KEY,
	src TEXT,   -- source url path
	dst TEXT,   -- destination url path
	type TEXT, -- type on why the dst was chosen
	status INTEGER DEFAULT 301 NOT NULL  -- http status code
);

-- blogs
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/ansible-and-infoblox','https://blog.alta3.com/topics/ansible/ansible-and-infoblox/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/install-virtualbox','https://blog.alta3.com/topics/linux/installing-virtualbox/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/installing+virtualbox','https://blog.alta3.com/topics/linux/installing-virtualbox/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/installing-virtualbox','https://blog.alta3.com/topics/linux/installing-virtualbox/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/ansible-switch-configuration-archive-tutorial','https://blog.alta3.com/topics/ansible/ansible-switch-config-archive/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/passing-the-ckad','https://blog.alta3.com/topics/kubernetes/crushckad/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/python-versions-python2-vs-python3','https://blog.alta3.com/topics/programming/python-versions-python2-vs-python3/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/restore-backed-up-files-using-ansible','https://blog.alta3.com/topics/ansible/restore-backed-up-files-using-ansible/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/8-steps-to-k8s-cluster','https://blog.alta3.com/topics/kubernetes/8-steps-to-k8s-cluster/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/introduction-to-kubernetes','https://blog.alta3.com/blogs/kubernetes/8-steps-to-k8s-cluster/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/adding-spell-checking-as-a-github-action','https://blog.alta3.com/topics/scm-and-pipelines/adding-spell-checking-as-a-github-action/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/ansible+switch+config+archive','https://blog.alta3.com/topics/ansible/ansible-and-infoblox/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/ansible-basics-tutorial','https://blog.alta3.com/topics/ansible/ansible-basics-tutorial/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/ansible-is-for-everyone','https://blog.alta3.com/topics/ansible/ansible-is-for-everyone/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/ansible-template-tutorial','https://blog.alta3.com/topics/ansible/ansible-template-tutorial/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/ansible-templates','https://blog.alta3.com/topics/ansible/ansible-templates/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/ansible-vault-hello-world','https://blog.alta3.com/topics/ansible/ansible-vault-hello-world/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/api-requests-with-python','https://blog.alta3.com/topics/api/api-requests-with-python/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/back-up-your-organizations-github','https://blog.alta3.com/topics/scm-and-pipelines/back-up-your-organizations-github/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/converting-html-to-markdown','https://blog.alta3.com/topics/programming/converting-html-to-markdown/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/create-pipeline','https://blog.alta3.com/topics/scm-and-pipelines/create-pipeline/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/creating-flask-server','https://blog.alta3.com/topics/programming/creating-flask-server/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/crushckad','https://blog.alta3.com/topics/kubernetes/crushckad/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/diagnosing-a-slow-network','https://blog.alta3.com/topics/networking/diagnosing-a-slow-network/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/error-invalid-value-apiall-on-kube-apiserver','https://blog.alta3.com/topics/kubernetes/error-invalid-value-apiall-on-kube-apiserver/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/fastapi','https://blog.alta3.com/topics/api/fastapi/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/getting-keyed-up','https://blog.alta3.com/topics/networking/getting-keyed-up/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/go-programming-print','https://blog.alta3.com/topics/programming/go-programming-print/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/gos-approach-to-arrays-and-slices','https://blog.alta3.com/topics/programming/gos-approach-to-arrays-and-slices/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/how-to-create-a-virtual-machine','https://blog.alta3.com/topics/linux/how-to-create-a-virtual-machine/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/how-to-install-terraform-infrastructure-as-code-tool','https://blog.alta3.com/topics/linux/how-to-install-terraform-infrastructure-as-code-tool/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/install-python-and-ansible','https://blog.alta3.com/topics/ansible/install-python-and-ansible/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/install-windows-terminal','https://blog.alta3.com/topics/linux/install-windows-terminal/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/installing-windows-subsystem-for-linux-2-wsl2','https://alta3.com/blog/installing-windows-subsystem-for-linux-2-wsl2',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/introduction-to-kubernetes','https://blog.alta3.com/topics/kubernetes/introduction-to-kubernetes/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/jinja-templates','https://blog.alta3.com/topics/programming/jinja-templates/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/launch-cloud-init-configured-vms','https://blog.alta3.com/topics/networking/launch-cloud-init-configured-vms/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/magic-the-gathering-api','https://blog.alta3.com/topics/api/magic-the-gathering-api/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/managing-github-issue-labels-across-organizations-and-repositories','https://blog.alta3.com/topics/scm-and-pipelines/managing-github-issue-labels-across-organizations-and-repositories/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/minus-28-bytes-later','https://blog.alta3.com/topics/networking/minus-28-bytes-later/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/-28-bytes-later','https://blog.alta3.com/topics/networking/minus-28-bytes-later/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/moving-active-k8s-cluster-on-qemu-vm','https://blog.alta3.com/topics/kubernetes/moving-active-k8s-cluster-on-qemu-vm/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/python-and-apis-nasas-open-apis','https://blog.alta3.com/topics/api/python-and-apis-nasas-open-apis/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/python-and-the-magic-wormhole-project','https://blog.alta3.com/topics/programming/python-and-the-magic-wormhole-project/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/python-apis-part2','https://blog.alta3.com/topics/api/python-apis-part2/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/python-tutorial-using-python-to-interact-with-excel','https://blog.alta3.com/topics/programming/python-versions-python2-vs-python3/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/pythonapi-part1','https://blog.alta3.com/topics/api/pythonapi-part1/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/restore-backed-up-files-using-ansible','https://blog.alta3.com/topics/ansible/restore-backed-up-files-using-ansible/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/securingdnsmasq','https://blog.alta3.com/topics/networking/securingdnsmasq/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/singlevmk8s','https://blog.alta3.com/topics/kubernetes/singlevmk8s/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/throttling-ansibles-localaction-module','https://blog.alta3.com/topics/ansible/throttling-ansibles-localaction-module/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/tune-your-dot-files','https://blog.alta3.com/topics/linux/tune-your-dot-files/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/ubuntu-1804-preseed-installation','https://blog.alta3.com/topics/linux/ubuntu-1804-preseed-installation/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/unlocking-your-vim-screen','https://blog.alta3.com/topics/linux/unlocking-your-vim-screen/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/vim-introduction-getting-started-with-vim','https://blog.alta3.com/topics/linux/vim-introduction-getting-started-with-vim/',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-post','/blog/vimcolorscheme','https://blog.alta3.com/topics/linux/vimcolorscheme/',301);

-- blog tags
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/kubernetes','https://blog.alta3.com/tags/kubernetes',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/curl','https://blog.alta3.com/tags/curl',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/kubernetes+cluster','https://blog.alta3.com/tags/kubernetes',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible+hosts','https://blog.alta3.com/tags/ansible_hosts',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/Restful+API','https://blog.alta3.com/tags/restful_api',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/networking','https://blog.alta3.com/tags/networking',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/python+tutorial','https://blog.alta3.com/tags/python',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/kubernetes+training','https://blog.alta3.com/tags/kubernetes',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/icmp','https://blog.alta3.com/tags/icmp',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/back-up','https://blog.alta3.com/tags/back_up',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/kubernetes+tutorial','https://blog.alta3.com/tags/kubernetes',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/online+ansible+training','https://blog.alta3.com/tags/ansible',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/Ansible+Tutorial','https://blog.alta3.com/tags/ansible',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/Init','https://blog.alta3.com/tags/init',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/automation','https://blog.alta3.com/tags/automation',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/dev','https://blog.alta3.com/tags/dev',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/vm%27s','https://blog.alta3.com/tags/vms',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/wsl2','https://blog.alta3.com/tags/wsl2',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/powershell','https://blog.alta3.com/tags/powershell',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/github+keys','https://blog.alta3.com/tags/github_keys',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/html','https://blog.alta3.com/tags/html',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/api','https://blog.alta3.com/tags/api',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/vim','https://blog.alta3.com/tags/vim',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible+certification','https://blog.alta3.com/tags/ansible_certification',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/Ansible+Training','https://blog.alta3.com/tags/ansible',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/programming','https://blog.alta3.com/tags/programming',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/webinar','https://blog.alta3.com/tags/webinar',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/python','https://blog.alta3.com/tags/python',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/github','https://blog.alta3.com/tags/github',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/linux+tutorial','https://blog.alta3.com/tags/linux',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ubuntu','https://blog.alta3.com/tags/ubuntu',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ckad','https://blog.alta3.com/tags/ckad',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/python+training','https://blog.alta3.com/tags/python',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/iperf','https://blog.alta3.com/tags/iperf',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/private+key','https://blog.alta3.com/tags/private_key',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/mtu','https://blog.alta3.com/tags/mtu',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/jinja2','https://blog.alta3.com/tags/jinja2',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/id_rsa.pub','https://blog.alta3.com/tags/id_rsa.pub',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible+tutorial','https://blog.alta3.com/tags/ansible',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/virtual+machine','https://blog.alta3.com/tags/virtual_machine',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/versions','https://blog.alta3.com/tags/versions',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/vm','https://blog.alta3.com/tags/vm',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/virtual+machines','https://blog.alta3.com/tags/virtual_machines',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/Ansible','https://blog.alta3.com/tags/ansible',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/http','https://blog.alta3.com/tags/http',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/youtube','https://blog.alta3.com/tags/youtube',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible+training','https://blog.alta3.com/tags/ansible',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/key+gen','https://blog.alta3.com/tags/key_gen',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/id_rsa','https://blog.alta3.com/tags/id_rsa',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/roles','https://blog.alta3.com/tags/roles',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/%23python','https://blog.alta3.com/tags/python',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/show','https://blog.alta3.com/tags/show',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible+template','https://blog.alta3.com/tags/ansible',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible+switch+config+archive','https://blog.alta3.com/tags/ansible_switch_config_archive',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/playbooks','https://blog.alta3.com/tags/playbooks',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/requests','https://blog.alta3.com/tags/requests',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/InfoBlox','https://blog.alta3.com/tags/InfoBlox',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible','https://blog.alta3.com/tags/ansible',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/keygen','https://blog.alta3.com/tags/keygen',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible+inventory','https://blog.alta3.com/tags/ansible_inventory',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/online+python+training','https://blog.alta3.com/tags/online_python_training',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/playlist','https://blog.alta3.com/tags/playlist',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/mtu+testing','https://blog.alta3.com/tags/mtu_testing',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/api+design','https://blog.alta3.com/tags/api_design',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/virtualbox','https://blog.alta3.com/tags/virtualbox',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/Ansible+Playbook','https://blog.alta3.com/tags/ansible_playbook',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/Network+Objects','https://blog.alta3.com/tags/network_objects',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/installing+virtualbox','https://blog.alta3.com/tags/installing_virtualbox',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/linux','https://blog.alta3.com/tags/linux',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/markdown','https://blog.alta3.com/tags/markdown',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/tutorial','https://blog.alta3.com/tags/tutorial',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/dsnmasq','https://blog.alta3.com/tags/dsnmasq',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/python+programming','https://blog.alta3.com/tags/python',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/installing+kubernetes','https://blog.alta3.com/tags/installing_kubernetes',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/api+design+with+python','https://blog.alta3.com/tags/api',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/k8s','https://blog.alta3.com/tags/k8s',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/vcs','https://blog.alta3.com/tags/vcs',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/Writing+API%27s+with+Python','https://blog.alta3.com/tags/python',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/windows','https://blog.alta3.com/tags/windows',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible+template+module','https://blog.alta3.com/tags/ansible_template_module',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/practices','https://blog.alta3.com/tags/practices',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/nasa','https://blog.alta3.com/tags/nasa',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/%23programmng','https://blog.alta3.com/tags/programmng',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible+eos+banner','https://blog.alta3.com/tags/ansible_eos_banner',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/virtual+box','https://blog.alta3.com/tags/virtual_box',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/windows+subsystem','https://blog.alta3.com/tags/windows_subsystem',301);
INSERT INTO redir (type, src, dst, status) VALUES ('blog-tag','/blog/tag/ansible+switch+configuration','https://blog.alta3.com/tags/ansible_switch_configuration',301);

-- blog category
INSERT INTO redir (type, src, dst, status) VALUES('blog-tag', '/blog/category/youtube','https://blog.alta3.com/tags/youtube',301);
INSERT INTO redir (type, src, dst, status) VALUES('blog-tag', '/blog/category/how-to','https://blog.alta3.com/tags/how_to',301);
INSERT INTO redir (type, src, dst, status) VALUES('blog-tag', '/blog/category/videos','https://blog.alta3.com/tags/video',302);
INSERT INTO redir (type, src, dst, status) VALUES('blog-tag', '/blog/category/blog','https://blog.alta3.com/',301);

-- instructors TODO: instructor ids
INSERT INTO redir (type, src, dst, status) VALUES('instructor', '/zach', '/instructors/',301);
INSERT INTO redir (type, src, dst, status) VALUES('instructor', '/chad', '/instructors/',301);
INSERT INTO redir (type, src, dst, status) VALUES('instructor', '/stu',  '/instructors/',301);
INSERT INTO redir (type, src, dst, status) VALUES('instructor', '/hutch','/instructors/',301);
INSERT INTO redir (type, src, dst, status) VALUES('instructor', '/jason','/instructors/',301);
INSERT INTO redir (type, src, dst, status) VALUES('instructor', '/paul', '/instructors/',301);
INSERT INTO redir (type, src, dst, status) VALUES('instructor', '/rob',  '/instructors/',301);
INSERT INTO redir (type, src, dst, status) VALUES('instructor', '/sean', '/instructors/',301);
INSERT INTO redir (type, src, dst, status) VALUES('instructor', '/tim',  '/instructors/',301);

-- courses
INSERT INTO redir (src, dst, status) VALUES('/overviewansible-for-dbas',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overviewpython-training-data-sciences',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overviewsdwantraining',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/suse-linux-rancher-k8s',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/certification-pyb',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/certification-pyna-202',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/certification-python-201',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-5g',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-5g',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-ai-chat-bard',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-ansible',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-ansible-1',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-ansible-102',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-ansible-202',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-ansible-203',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-ansible-302',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-ansible-ai',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-api-python-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-automation-python-ansible-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-c98wf6',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-ci/cd-pipelines',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-circleci-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-cka-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-cks',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-crush-the-ckad',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-dcucai',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-deploying5g',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-devsecops',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-django',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-docker-1',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-docker101',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-github-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-gitlab-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-golang-ai',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-golang-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-idswots',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-intucsx',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-ipsec-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-java-ai',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-jenkins-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-kubernetes-ckad',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-linux-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-mastering-ansible-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-microservices-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-natural-language-ai',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-opensource-ai',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-opensource-ai-dell',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-openstack-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-packer',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-prompt-engineering',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-python-ai',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-python-ai-1',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-python-basics-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-python-network-automation',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-rancher-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-sdn-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-sdn-trainingnopvc',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-sip',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-sles-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-suse-k8s',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-suse-neuvector',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-tcp-ip',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-terraform',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-terraform-102',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-terraform-103-paloalto',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-terraform-104-fortinet',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-terraform-special',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-volte',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-zerocode-ai',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-zerocodechatbots',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-zerocodechatbots-chatgpt',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/overview-zerocodechatbots-watson',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-ai-bard',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-ansible-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-api-python-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-certified-kubernetes-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-cks',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-django',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-gitlab-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-ipsec-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-jenkins-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-kubernetes-ckad',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-linux-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-microservices-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-network-automation-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-neuvector',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-nlp-ai',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-openstack-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-os-generative-ai',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-prompt-engineering',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-python-automation-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-python-basics-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-python-data-sciences-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-rancher-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-sdn-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-sip',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-slesv201v15-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-suse-k8s-training',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-terraform',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store-volte',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/2z334d2ojyyeh9u04uhj2oa1wsfmg5',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/5g-essentials-online-live-class-apr2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/5g-essentials-online-live-class-april2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/5g-essentials-online-live-class-august27-28',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/5g-essentials-online-live-class-feb2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/5g-essentials-online-live-class-jan2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/5g-essentials-online-live-class-jan2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/5g-essentials-online-live-class-june2021-k5rbs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/5g-essentials-online-live-class-nov2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/5g-essentials-online-live-class-sept2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/5g-essentials-self-paced-course',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/agile-8-2021-w9dhj-a8sad',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/agile10-2021-w9dhj',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ansible-essentials-online-feb2024-r3ptk',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ansible-essentials-online-may2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ansible-essentials-online-may2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ansible-essentials-self-paced',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ansible-essentials-self-paced-ans2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ansible-essentials-self-paced-nov2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ansible-manual',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ansible-palo-alto-aug2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ansible-practice-labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/api-design-with-python-feb-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/api-design-with-python-jan2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/api-design-with-python-july2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/api-design-with-python-may2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/api-design-with-python-nov2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/api-design-with-python-nov2021-f5ebn',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/api-design-with-python-sept2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/api-design-with-python-sept2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/api-practice-labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/apis-and-api-design-with-python-april2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/apis-and-api-design-with-python-june-1-5-jmz9w',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/apis-and-api-design-with-python-june2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/apis-and-api-design-with-python-nov2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/appdev-august2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/appdev-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/appdev-oct2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/architecting-on-aws-online-live-423',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/architecting-on-aws-online-live-aug-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/architecting-on-aws-online-live-aug31',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/architecting-on-aws-online-live-aug32021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/architecting-on-aws-online-live-class-4-5-22',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/architecting-on-aws-online-live-july20',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/architecting-on-aws-online-live-nov-21',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/architecting-on-aws-online-live-oct-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-techessentials-jan9',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-05-16-22',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-6-27',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-online-live-class-8-22',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-online-live-class-apr2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-online-live-class-aug17',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-online-live-class-jan2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-online-live-class-july2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-online-live-class-june2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-online-live-class-may2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-online-live-class-oct19',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentials-sept-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentialsoct2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/aws-technical-essentialsoct2021-ny3rx',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/big-data-on-aws-online-live-class-apr2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/big-data-on-aws-online-live-class-dec8',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/big-data-on-aws-online-live-class-oct13',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/c98wf6-april2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/c98wf6-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/c98wf6-may2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/certified-ethical-hacker-may2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/certified-ethical-hacker-v10',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/certified-kubernetes-administrator-labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ci/cd/july-2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ci/cd/oct2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cissp-boot-camp-online-live-dec2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cissp-boot-camp-online-live-nov2020-737ye',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-online-live-class-april2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-online-live-class-april2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-online-live-class-aug2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-online-live-class-feb2021-bgrm8',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-online-live-class-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-online-live-class-nov2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-online-live-class-oct2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-online-live-class-sep2021-w7p82',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-practice-labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-self-paced-5fj6w',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cka-selfpaced',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cks-april2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cks-jully2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/cks-sept2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-advanced-security-practitioner-casp-dec-gpcyn',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-advanced-security-practitioner-casp-dec-gpcyn-m25px',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-casp-april2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-casp-sept21',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-network-online-live-nightclassaugust',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-network-online-live-nightclassaugust-5lgcw',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-network-online-live-sept-28-oct-2-800-am-to-400-pm-est',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-security-boot-camp-apr2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-security-boot-camp-april-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-security-boot-camp-aug2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-security-boot-camp-dec2021-g29rp',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-security-boot-camp-march-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-security-boot-camp-march-may-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-security-boot-camp-nov2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/comptia-security-boot-camp-nov2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/crush-the-ckad',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/dcucai-april2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/dcucai-may2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/deploying5g-online-live-class-12-21',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/deploying5g-online-live-class-april2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/deploying5g-online-live-class-jan2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/developing-on-aws-online-live-class-4-26-22',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/developing-on-aws-online-live-class-apr2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/developing-on-aws-online-live-class-aug-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/developing-on-aws-online-live-class-aug10',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/developing-on-aws-online-live-class-july-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/developing-on-aws-online-live-class-june2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/developing-on-aws-online-live-class-may2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/developing-on-aws-online-live-class-oct-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/devops-8-2021-w9dhj',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/devops-9-28-21',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/devops-foundations-10-212021-jd5t2-cjlzd',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/devops-foundations-9-212021-jd5t2',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/devops-foundations-9-7-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/gitlab-training-jan2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/gitlab-training-march2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/gitlab-training-oct2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/gitlab-training-oct2021-9hkpn-Bhi6h',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/go-practice-labs-3678w',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/golang-aug2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/golang-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/intucxs-april2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/intucxs-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/intucxs-march2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/ipsec-self-paced-course',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkins-aug2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkins-feb2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkins-jan-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkins-jan2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkins-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkins-march2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkins-oct2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkins-practice-labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkins-sept2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkinsmay2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/jenkinsnov2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/k8s-ckad-practice-labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-bootcamp-online-live-class-aug2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-bootcamp-online-live-class-august31',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-bootcamp-online-live-class-dec2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-bootcamp-online-live-class-jan2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-bootcamp-online-live-class-nov2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-bootcamp-online-live-class-oct2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-bootcamp-online-live-class-spet2023',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-bootcamp-self-paced',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-ckad-online-live-class-dec2023',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-online-live-class-april2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-online-live-class-aug2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-online-live-class-july-2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-online-live-class-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetes-online-live-class-oct-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/kubernetesonlineliveclassapril2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/microservices-online-live-class-1-27-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/microservices-online-live-class-aug2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/microservices-online-live-class-jan2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/microservices-online-live-class-june2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/microservices-online-live-class-march2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/microservices-online-live-class-march2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/microservices-online-live-class-oct2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/microservices-practice-labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/napya-july2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/napya-may2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/napya-may2024-zlah6',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/network-automation-python-ansible-practice-labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/network-automation-with-python-and-ansible-online-live-class-april2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/network-automation-with-python-and-ansible-online-live-class-aug2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/network-automation-with-python-and-ansible-online-live-class-dec2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/network-automation-with-python-and-ansible-online-live-class-feb2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/network-automation-with-python-and-ansible-online-live-class-june-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/network-automation-with-python-and-ansible-online-live-class-oct2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/network-automation-with-python-and-ansible-online-live-class-oct2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/os-generative-ai-aug2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/os-generative-ai-july2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/os-generative-ai-may2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/pe-ai-april24',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/pe-ai-aug2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/pe-ai-oct2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/pe-june-2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/pyai-april2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/pyai-aug2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-class-april2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-class-aug2021-jjl47',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-class-dec2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-class-jan2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-class-jul2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-class-march2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-class-may2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-class-nov2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-class-nov2021-swamm',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-class-oct2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-july2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-nov2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-online-live-sept2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-basics-self-paced',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-network-automation-self-paced',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-practice-labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/python-practice-labs-9t8mr',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/pythonnetworautomation-aug2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/pythonnetworautomation-aug2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/pythonnetworautomation-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/pythonnetworautomation-march2023',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/red-hat-system-administrator-online-live-jan2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/red-hat-system-administrator-online-live-july2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/red-hat-system-administrator-self-paced',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/rhcsa-oct2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sd-wan-online-live-class-oct-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sdn-practice-labs',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sdnnfv-online-live-class-oct2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sdnnfv-self-paced',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sdwots-april',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sdwots-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sip-essentials-online-live-class-april2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sip-essentials-online-live-class-dec2020',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sip-essentials-online-live-july2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sip-essentials-online-live-oct2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sip-online-live-apr2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sip-online-live-dec-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sip-online-live-dec2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sip-online-live-june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sip-online-live-sept2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sip-self-paced',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/sp-ansible-201',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/subscription-mnthly',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-k8s-april2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-k8s-aug2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-k8s-dec2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-k8s-jan2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-k8s-july2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-k8s-may2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-k8s-oct2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-k8s-october2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-rancher-apr2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-rancher-aug2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-rancher-aug2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-rancher-dec2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-rancher-july2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-rancher-may2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-rancher-oct2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-rancher-october2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-sle201v15-linux-sept2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-sles-linux-apr2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-sles-linux-june2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/suse-sles-linux-nov2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/system-operations-on-aws-online-live-class-apr2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/system-operations-on-aws-online-live-class-aug-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/system-operations-on-aws-online-live-class-jan2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/system-operations-on-aws-online-live-class-july2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/system-operations-on-aws-online-live-class-june2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/system-operations-on-aws-online-live-class-mar2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/system-operations-on-aws-online-live-class-may2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/system-operations-on-aws-online-live-class-may2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/system-operations-on-aws-online-live-class-oct-2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/system-operations-on-aws-online-live-class-sept2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/terraform/april2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/terraform/aug2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/terraform/june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/terraform/may2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/terraform/oct2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/terraform102/august2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/terraform102/june2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/tf-selfpaced',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/volte-and-the-ims-online-training-livesept-584p6mar2022',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/volte-and-the-ims-onlinelivesept',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/volte-and-the-ims-self-paced-course',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/volte-online-training-june2021',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/zerocode-10-2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/zerocode-4-2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/zerocode-6-2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/p/zerocode-8-2024',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/self-paced',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/store/virtual',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/storecirclecitraining',NULL,301);
INSERT INTO redir (src, dst, status) VALUES('/storegolangtraining',NULL,301);

-- to other domains
INSERT INTO redir (type, src, dst, status) VALUES('different-domain','/blog','https://blog.alta3.com/',301);
INSERT INTO redir (type, src, dst, status) VALUES('different-domain','/cloud-devops-tutorials','https://blog.alta3.com/',301);
INSERT INTO redir (type, src, dst, status) VALUES('different-domain','/posters','https://blog.alta3.com/posters',301);

-- contact
INSERT INTO redir (type, src, dst, status) VALUES('contact','/contact','/contact-us',301);
INSERT INTO redir (type, src, dst, status) VALUES('contact','/free-course-trials','/',301);
INSERT INTO redir (type, src, dst, status) VALUES('contact','/free-course-trials-thank-you','/',301);

-- primary
INSERT INTO redir (src, dst, status) VALUES('/training-courses','/courses',301);
INSERT INTO redir (src, dst, status) VALUES('/training-courses-2','/courses',301);
INSERT INTO redir (src, dst, status) VALUES('/store','/courses',301);

-- careers
INSERT INTO redir (type, src, dst, status) VALUES('careers','/instructor-application','/careers',301);
INSERT INTO redir (type, src, dst, status) VALUES('careers','/instructor-application-1','/careers',301);
INSERT INTO redir (type, src, dst, status) VALUES('careers','/sales-application','/careers',301);

-- events
INSERT INTO redir (type, src, dst, status) VALUES('events','/events-online-training','/schedule',301);
INSERT INTO redir (type, src, dst, status) VALUES('events','/july-sles-webinar','/schedule',301);
INSERT INTO redir (type, src, dst, status) VALUES('events','/kubernetes-5g-webinar','/schedule',301);
INSERT INTO redir (type, src, dst, status) VALUES('events','/kubernetes-in-the-5g-network-webinar','/schedule',301);
INSERT INTO redir (type, src, dst, status) VALUES('events','/march-suse-rancher-webinar','/schedule',301);
INSERT INTO redir (type, src, dst, status) VALUES('events','/may-ansible-awx-webinar','/schedule',301);

-- 404 ( TODO: remove?)
INSERT INTO redir (type, src, dst, status) VALUES('404','/alta3-logo','/',301);
INSERT INTO redir (type, src, dst, status) VALUES('404','/course-not-available','/',301);
INSERT INTO redir (type, src, dst, status) VALUES('404','/draftpagedonotlink','/',301);
INSERT INTO redir (type, src, dst, status) VALUES('404','/subscription-services','/',301);
INSERT INTO redir (type, src, dst, status) VALUES('404','/certificates','/',301);
INSERT INTO redir (type, src, dst, status) VALUES('404','/testimonials','/',301);
INSERT INTO redir (type, src, dst, status) VALUES('404','/terms-and-conditions','/',301);

-- offereing types type, -- TODO: add routes to offereing types
INSERT INTO redir (type, src, dst, status) VALUES('offerings','/on-demand-courses','/',302);
INSERT INTO redir (type, src, dst, status) VALUES('offerings','/classroom-live','/',302);
INSERT INTO redir (type, src, dst, status) VALUES('offerings','/store/manual','/',302);
INSERT INTO redir (type, src, dst, status) VALUES('offerings','/store/online-live','/',301);

-- categories TODO:type,  category ids at path
INSERT INTO redir (type, src, dst, status) VALUES('categories','/ai-training','/courses',302);
INSERT INTO redir (type, src, dst, status) VALUES('categories','/ansible-training','/courses',302);
INSERT INTO redir (type, src, dst, status) VALUES('categories','/cisco-training','/courses',302);
INSERT INTO redir (type, src, dst, status) VALUES('categories','/cloud-training','/courses',302);
INSERT INTO redir (type, src, dst, status) VALUES('categories','/devops','/courses',302);
INSERT INTO redir (type, src, dst, status) VALUES('categories','/docker-training','/courses',302);
INSERT INTO redir (type, src, dst, status) VALUES('categories','/programming-training','/courses',302);
INSERT INTO redir (type, src, dst, status) VALUES('categories','/kubernetes','/courses',302);
INSERT INTO redir (type, src, dst, status) VALUES('categories','/telecom-courses','/courses',302);

COMMIT;
